### PR TITLE
Added stockpics fragment and rv

### PR DESCRIPTION
**Pull request by hchan22**
yay fragment w/ recyclerview of stock memes

### CODE REVIEW

**Comment by cito125** [comment]
# Can't see meme list when I open your fragment, although I saw it on your phone so idk what the issue is

**Comment by hchan22** [comment]
The fragment is not called.  You can test it by calling in the MainActivity.  Change homeFragment to StockPicsFragment in setupviewpager method.  I think this rv is supposed be called in the floating button so I took it off

**Comment by cito125** [comment]
Yeah, I mean I did that and I don't see a recyclerview

**Comment by cito125** [comment]
Does it work on your emulator?

**Pull request closed without merging**
